//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rz.DddDemo.PurchaseHistoryProviderClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPurchasesRequest", Namespace="http://schemas.datacontract.org/2004/07/Rz.DddDemo.PurchaseHistoryProviders.Provi" +
        "derC.Contract")]
    public partial class GetPurchasesRequest : object
    {
        
        private string CustomerIdField;
        
        private bool IncludeReturnedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeReturned
        {
            get
            {
                return this.IncludeReturnedField;
            }
            set
            {
                this.IncludeReturnedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPurchasesResponse", Namespace="http://schemas.datacontract.org/2004/07/Rz.DddDemo.PurchaseHistoryProviders.Provi" +
        "derC.Contract")]
    public partial class GetPurchasesResponse : object
    {
        
        private Rz.DddDemo.PurchaseHistoryProviderClient.Purchase[] PurchasesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rz.DddDemo.PurchaseHistoryProviderClient.Purchase[] Purchases
        {
            get
            {
                return this.PurchasesField;
            }
            set
            {
                this.PurchasesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchase", Namespace="http://schemas.datacontract.org/2004/07/Rz.DddDemo.PurchaseHistoryProviders.Provi" +
        "derC.Contract")]
    public partial class Purchase : object
    {
        
        private System.DateTime DateField;
        
        private Rz.DddDemo.PurchaseHistoryProviderClient.Item[] ItemsField;
        
        private bool ReturnedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rz.DddDemo.PurchaseHistoryProviderClient.Item[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Returned
        {
            get
            {
                return this.ReturnedField;
            }
            set
            {
                this.ReturnedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Rz.DddDemo.PurchaseHistoryProviders.Provi" +
        "derC.Contract")]
    public partial class Item : object
    {
        
        private int CountField;
        
        private string NameField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Rz.DddDemo.PurchaseHistoryProviderClient.ICustomerDataService")]
    public interface ICustomerDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerDataService/GetPurchases", ReplyAction="http://tempuri.org/ICustomerDataService/GetPurchasesResponse")]
        System.Threading.Tasks.Task<Rz.DddDemo.PurchaseHistoryProviderClient.GetPurchasesResponse> GetPurchasesAsync(Rz.DddDemo.PurchaseHistoryProviderClient.GetPurchasesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ICustomerDataServiceChannel : Rz.DddDemo.PurchaseHistoryProviderClient.ICustomerDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CustomerDataServiceClient : System.ServiceModel.ClientBase<Rz.DddDemo.PurchaseHistoryProviderClient.ICustomerDataService>, Rz.DddDemo.PurchaseHistoryProviderClient.ICustomerDataService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerDataServiceClient() : 
                base(CustomerDataServiceClient.GetDefaultBinding(), CustomerDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICustomerDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerDataServiceClient.GetBindingForEndpoint(endpointConfiguration), CustomerDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Rz.DddDemo.PurchaseHistoryProviderClient.GetPurchasesResponse> GetPurchasesAsync(Rz.DddDemo.PurchaseHistoryProviderClient.GetPurchasesRequest request)
        {
            return base.Channel.GetPurchasesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerDataService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerDataService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59705/CustomerDataService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICustomerDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerDataServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICustomerDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICustomerDataService,
        }
    }
}
